# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Time Series Exploration with Python, A Journey from Traditional to Advanced Forecasting Models
author: Farid Jabbari Maleki
advisor: Dr. Milad Totounchian
#logo: logo.svg
copyright: "2023"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Set max run time for a cell
execute:
  execute_notebooks: off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/faridjb/Time-Series-Exploration  # Online location of your book at github e.g. https://github.com/weisscharlesj/SciCompforChemists 
  path_to_book: notebooks  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: true  # Whether to include your home page in the left Navigation Bar
  # extra_navbar: Powered by <a href="https://jupyterbook.org/">Jupyter Book</a>
  extra_footer:  LinkedIn <a href="https://www.linkedin.com/in/farid-j-maleki/">Farid J. Maleki</a>
